### PR TITLE
modify cookies_file (add[:2]) in save_cookies_to_local

### PR DESCRIPTION
**Pull request by YuTao0310**
When the nickname is too long, the cookie file cannot be created correctly. I think we can get a substring of a full nickname become the name of cookie file.

### CODE REVIEW

**Comment by YuTao0310** [comment]
Maybe a area_id directory and a get_eid_fp.html can be added.

**Comment by louisyoungx** [comment]
looks great! thank you!

**Comment by louisyoungx** [comment]
However, the `area_id/` directory and `get_eid_fp.html` are duplicated because I put them in the `TEST/` directory.

**Comment by YuTao0310** [comment]
> However, the `area_id/` directory and `get_eid_fp.html` are duplicated because I put them in the `TEST/` directory.

Yeah, I don't mention it and the commit is redunctant. By the way, your repository helps me a lot. I hope I can get the goods in JD tomorrow.

**Comment by louisyoungx** [comment]
> 

Thanks, good luck!!!
I will merge this pr

**Pull request merged**
